-- Cassen waitlist schema — hardened.
-- Run in the Supabase SQL editor for project "cassen".
--
-- If you previously ran an older version of this file, drop the table first
-- (only safe before any real signups have come in):
--   drop table if exists public.waitlist cascade;
--
-- Threat model:
--   - All writes/reads happen server-side using the service-role key (which
--     bypasses RLS). No browser code ever touches this table directly.
--   - Anon and authenticated roles get zero access. Even if the anon key
--     leaks (it always does — it ships in the bundle), the worst an attacker
--     can do is hit auth/storage/etc., never this table.
--   - CHECK constraints are the last line of defense against malformed or
--     oversized payloads if the app-layer Zod validation is ever bypassed.

-- --------------------------------------------------------------------------
-- Extensions
-- --------------------------------------------------------------------------
create extension if not exists citext;

-- --------------------------------------------------------------------------
-- Table
-- --------------------------------------------------------------------------
create table if not exists public.waitlist (
  id          bigint generated by default as identity primary key,
  email       citext  not null,
  referrer    text,
  metadata    jsonb,
  approved    boolean not null default false,
  position    bigint  generated always as (id) stored,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint waitlist_email_unique unique (email),

  constraint waitlist_email_length_chk
    check (char_length(email::text) between 3 and 320),

  -- Pragmatic email-shape check; the canonical validation lives in the app.
  constraint waitlist_email_format_chk
    check (email ~* '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$'),

  constraint waitlist_referrer_length_chk
    check (referrer is null or char_length(referrer) <= 256),

  -- Cap arbitrary jsonb at 4 KB to prevent payload abuse.
  constraint waitlist_metadata_size_chk
    check (metadata is null or octet_length(metadata::text) <= 4096)
);

create index if not exists waitlist_created_at_idx
  on public.waitlist (created_at desc);

-- --------------------------------------------------------------------------
-- updated_at trigger (search_path locked for hardening)
-- --------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists waitlist_set_updated_at on public.waitlist;
create trigger waitlist_set_updated_at
  before update on public.waitlist
  for each row
  execute function public.set_updated_at();

-- --------------------------------------------------------------------------
-- RLS: enable + force, drop any prior permissive policies, revoke privileges.
-- No policies are created => anon and authenticated cannot select/insert/
-- update/delete anything. The service role bypasses RLS entirely, so the
-- server-side signup action and admin reads continue to work.
-- --------------------------------------------------------------------------
alter table public.waitlist enable row level security;
alter table public.waitlist force  row level security;

drop policy if exists "anon can insert" on public.waitlist;

revoke all on table public.waitlist from public;
revoke all on table public.waitlist from anon;
revoke all on table public.waitlist from authenticated;

grant all on table public.waitlist to service_role;

-- ==========================================================================
-- Editable site content (CMS)
-- ==========================================================================
-- One row per editable section of the landing page. Reads happen via service
-- role on the server; writes happen via admin server actions (also service
-- role). Browser code never touches this table.

create table if not exists public.site_content (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now(),

  constraint site_content_key_format_chk
    check (key ~ '^[a-z][a-z0-9_]{0,63}$'),

  constraint site_content_value_size_chk
    check (octet_length(value::text) <= 65536)
);

drop trigger if exists site_content_set_updated_at on public.site_content;
create trigger site_content_set_updated_at
  before update on public.site_content
  for each row
  execute function public.set_updated_at();

alter table public.site_content enable row level security;
alter table public.site_content force  row level security;

revoke all on table public.site_content from public;
revoke all on table public.site_content from anon;
revoke all on table public.site_content from authenticated;

grant all on table public.site_content to service_role;

-- --------------------------------------------------------------------------
-- Storage bucket for admin-uploaded assets (founder photo, etc.).
-- Public for read so the site can <img src=...> directly. Writes happen via
-- service-role from the admin server actions.
-- --------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('public-assets', 'public-assets', true)
on conflict (id) do nothing;
